=== k-zen/Quary/src/resources/definitions/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2015, Andreas P. Koenzen <akc at apkc.net>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="fields" type="Fields"/>
    <xs:element name="field" type="Field"/>
    <xs:element name="lucenevars" type="LuceneVars"/>
    <xs:element name="generalproperties" type="GeneralProperties"/>
    
    <xs:complexType name="Fields">
        <xs:sequence>
            <xs:element name="field" maxOccurs="unbounded" type="Field"/>
        </xs:sequence>
        <xs:attribute name="definitionID" type="xs:string" use="required"/>
        <xs:attribute name="scoreCoeficient" type="xs:float" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="Field">
        <xs:sequence>
            <xs:element name="lucenevars" maxOccurs="1" type="LuceneVars"/>
            <xs:element name="generalproperties" maxOccurs="1" type="GeneralProperties"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="LuceneVars">
        <xs:sequence>
            <xs:element name="analyzer" type="xs:byte" minOccurs="1" maxOccurs="1"/>
            <xs:element name="boost" type="xs:float" minOccurs="1" maxOccurs="1"/>
            <xs:element name="docvaluetype" type="xs:byte" minOccurs="0" maxOccurs="1"/>
            <xs:element name="indexed" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
            <xs:element name="indexoptions" type="xs:byte" minOccurs="0" maxOccurs="1"/>
            <xs:element name="numericprecisionstep" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="numerictype" type="xs:byte" minOccurs="0" maxOccurs="1"/>
            <xs:element name="omitnorms" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="stored" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
            <xs:element name="storetermvectoroffsets" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="storetermvectorpayloads" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="storetermvectorpositions" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="storetermvectors" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
            <xs:element name="tokenized" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="GeneralProperties">
        <xs:sequence>
            <xs:element name="contentencoding" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="searchable" type="xs:boolean" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== k-zen/Quary/src/resources/definitions/TestDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2015, Andreas P. Koenzen <akc at apkc.net>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
-->
<fields 
    definitionID="000"
    scoreCoeficient="1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="Schema.xsd">
    <!-- FULL EXAMPLE
        <field>
            <lucenevars>
                <analyzer>0|1</analyzer>
                <boost>0.0</boost>
                <docvaluetype>BINARY|NUMERIC|SORTED|SORTED_SET</docvaluetype>
                <indexed>0|1</indexed>
                <indexoptions>DOCS_AND_FREQS|DOCS_AND_FREQS_AND_POSITIONS|DOCS_AND_FREQS_AND_POSITIONS_AND_OFFSETS|DOCS_ONLY</indexoptions>
                <numericprecisionstep>4</numericprecisionstep>
                <numerictype>DOUBLE|FLOAT|INT|LONG</numerictype> 
                <omitnorms>0|1</omitnorms>
                <stored>0|1</stored>
                <storetermvectoroffset>0|1</storetermvectoroffset>
                <storetermvectorpayloads>0|1</storetermvectorpayloads>
                <storetermvectorpositions>0|1</storetermvectorpositions>
                <storetermvectors>0|1</storetermvectors>
                <tokenized>0|1</tokenized>
                <value>NAME_OF_FIELD</value>
            </lucenevars>
            <generalproperties>
                <contentencoding>NONE|BASE64</contentencoding> # Encoding of text inside the XML for indexing.
                <searchable>0|1</searchable>                   # If this field is searchable.
            </generalproperties>
        </field>
    -->
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>10.8</boost>
            <indexed>1</indexed>
            <stored>0</stored>
            <tokenized>1</tokenized>
            <value>anchor</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>boost</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>boostwithgravity</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>10.8</boost>
            <indexed>1</indexed>
            <stored>0</stored>
            <tokenized>1</tokenized>
            <value>content</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>BASE64</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>12.0</boost>
            <indexed>1</indexed>
            <stored>0</stored>
            <tokenized>1</tokenized>
            <value>contentraw</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>BASE64</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>11.4</boost>
            <indexed>1</indexed>
            <stored>0</stored>
            <tokenized>1</tokenized>
            <value>contentfilter</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>BASE64</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>0</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>contentlength</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>digest</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>9.6</boost>
            <indexed>1</indexed>
            <stored>0</stored>
            <tokenized>0</tokenized>
            <value>domain</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>0</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>fetchtime</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>filetype</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>0</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>gravity</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>8.4</boost>
            <indexed>1</indexed>
            <stored>0</stored>
            <tokenized>1</tokenized>
            <value>host</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>1</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>indextime</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>itsecond</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>itminute</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
            <analyzer>1</analyzer>
            <boost>6.0</boost>
            <indexed>1</indexed>
            <stored>1</stored>
            <tokenized>0</tokenized>
            <value>ithour</value>
        </lucenevars>
        <generalproperties>
            <contentencoding>NONE</contentencoding>
            <searchable>0</searchable>
        </generalproperties>
    </field>
    <field>
        <lucenevars>
